HartreeFock
friend class Nucleus
Interaction<double> HartreeFock::ME
Referenced by HartreeFock, Mean_Field, Hamiltonian, Diagonalization, Initialization, AMP, Nucleus::Spectral.
Interaction<cx_double> HartreeFock::ME_HF
Referenced by Construct_ME, Nucleus::Spectral.
int HartreeFock::MassNumber[Interaction< double >::IsoSpin_Z+1][Interaction< double >::IsoSpin_Z+1]
Referenced by HartreeFock, Diagonalization, Initialization, AMP, Nucleus::Construct_Configuration, Nucleus::Spectral.
cx_mat HartreeFock::rho[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by Diagonalization.
cx_mat HartreeFock::bra[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by Diagonalization, Initialization, DBP, Nucleus::Spectral.
cx_mat HartreeFock::ket[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by Diagonalization, Initialization, DBP, Nucleus::Spectral.
cx_mat HartreeFock::V_mf[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by HartreeFock, Diagonalization.
cx_mat HartreeFock::H_sp[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by Diagonalization.
vec HartreeFock::E_sp[Interaction< double >::IsoSpin_Z][Interaction< double >::IsoSpin_Z]
Referenced by Diagonalization, Iteration, Nucleus::Construct_Configuration.
double HartreeFock::BE
Referenced by Diagonalization, Iteration.
HartreeFock::HartreeFock(int Z, int A, string space, string force)
References MassNumber, ME, Interaction< T >::Dimension_M, V_mf.
HartreeFock::~HartreeFock()
void HartreeFock::Density_Matrix(T1 &psil, T2 &psir, cx_mat &rhoij, cx_double &overlap)
Subroutine to compute rho(i,j) for two SD's that are not orthogonal using a matrix representation.
psir right SD psil left SD rhoij: density matrix < psil | a^ a_j | psir > overlap: < psil | psir >
Referenced by Diagonalization, AMP.
void HartreeFock::Mean_Field(ivec *index, vec *tbme, cx_mat *rhoij, cx_mat *gamma)
Calculates mean-field matrix.
Index(i) list of (packed) nonzero indices, i = 1 to nmatpp to get indices IJKL of i'th matrix element do UNPACK(Index) TBME(i) ith TBME associated with indices unpacked from Index(i) rhopij/rhonij density matices for protons/neutrons gammap/gamman: Gamma matrix for protons/neutrons
References ME, Interaction< T >::unpack.
Referenced by Diagonalization.
void HartreeFock::Hamiltonian_sp(mat &e_sp, cx_mat &gamma, cx_mat &ham)
Calculates matrix h=T+Gamma.
e_sp(i j) one-body matrix element between i,j m-states gamma Gamma matrix Hamiltonian_sp
Referenced by Diagonalization.
cx_double HartreeFock::Hamiltonian(mat *e_sp, ivec *index, vec *tbme, cx_mat *rhoij, cx_double *overlap)
< psil | H | psir >
e_sp(i j) one-body matrix element between i,j m-states Index(i) list of (packed) nonzero indices, i = 1 to nmatpp to get indices IJKL of i'th matrix element do UNPACK(Index) TBME(i) ith TBME associated with indices unpacked from Index(i) rhoij density matrix < psil | a^ a_j | psir > < psil | H | psir >
References ME, Interaction< T >::unpack.
Referenced by Diagonalization, AMP.
void HartreeFock::Diagonalization()
Diagonlization single particle Harmiltonian.
Hamiltonian_sp Energies Wavefunctions
References bra, MassNumber, ket, Density_Matrix, rho, Mean_Field, ME, Interaction< T >::index, Interaction< T >::TBME, V_mf, Broyden, Hamiltonian_sp, Interaction< T >::OBME, H_sp, E_sp, BE, Hamiltonian.
Referenced by Iteration.
void HartreeFock::Initialization()
Initialize the HF wavefunction.
Bra_WF Ket_WF
References ME, Interaction< T >::Dimension_M, MassNumber, bra, ket.
Referenced by Iteration.
void HartreeFock::Iteration()
References Initialization, BE, Diagonalization, E_sp.
Referenced by Nucleus::Spectral.
void HartreeFock::Broyden(cx_mat *m)
Referenced by Diagonalization.
void HartreeFock::Rotation(double alpha, double beta, double gamma, T1 &src, T2 &dest, J_Orbit *jscheme, M_State *mscheme, int dim)
Rotate a state.
Wavefunction Rotated Wavefunction
References J_Orbit::j, M_State::m, Wigner_Function::Wigner_D_Matrix.
Referenced by AMP.
void HartreeFock::Space_Inversion(cx_mat &src, cx_mat &dest, M_State *mscheme)
Parity projection.
Wavefunction Wavefunction with space inversed
Referenced by AMP.
void HartreeFock::AMP(cx_mat *psil, cx_mat *psir, vec &J, vec &Parity, cx_vec &H, cx_vec &N)
Angular momentum projection.
Bra_WF Ket_WF J angular momentum P parity Hamiltonian
References MassNumber, Rotation, ME, Interaction< T >::J_scheme, Interaction< T >::M_scheme, Interaction< T >::Dimension_J, Density_Matrix, Hamiltonian, Interaction< T >::OBME, Interaction< T >::index, Interaction< T >::TBME, Space_Inversion, Wigner_Function::Wigner_D_Matrix.
Referenced by DBP, Nucleus::Spectral.
cx_double HartreeFock::Construct_ME(ivec &psil, ivec &psir)
References unpack, ME_HF, Interaction< T >::OBME, Interaction< T >::index, Interaction< T >::unpack, Interaction< T >::TBME, Count_Particle.
Referenced by Nucleus::Spectral.
void HartreeFock::HW_Equation_Hermitian(cx_mat &A, cx_mat &B, vec &val, cx_mat &wf)
Referenced by DBP, Nucleus::Spectral.
void HartreeFock::DBP()
References AMP, bra, ket, HW_Equation_Hermitian.
int HartreeFock::pack(ivec &config)
Referenced by Nucleus::Spectral.
ivec HartreeFock::unpack(int config)
Referenced by Construct_ME.
int HartreeFock::Count_Particle(int config)
Referenced by Construct_ME.