Interaction
const int Interaction< T >::IsoSpin_Z
Referenced by Interaction< T >::Interaction.
int Interaction< T >::Dimension_M[IsoSpin_Z][IsoSpin_Z]
Referenced by HartreeFock::HartreeFock, HartreeFock::Initialization.
int Interaction< T >::Dimension_J[IsoSpin_Z][IsoSpin_Z]
Referenced by Interaction< T >::Interaction, HartreeFock::AMP.
J_Orbit* Interaction< T >::J_scheme[IsoSpin_Z][IsoSpin_Z]
Referenced by Interaction< T >::Interaction, HartreeFock::AMP.
M_State* Interaction< T >::M_scheme[IsoSpin_Z][IsoSpin_Z]
Referenced by HartreeFock::AMP.
ivec Interaction< T >::index[IsoSpin_Z+1][IsoSpin_Z+1]
Referenced by Interaction< T >::Basis_Transform, HartreeFock::Diagonalization, HartreeFock::AMP, HartreeFock::Construct_ME.
Col<T> Interaction< T >::TBME[IsoSpin_Z+1][IsoSpin_Z+1]
Referenced by Interaction< T >::Basis_Transform, HartreeFock::Diagonalization, HartreeFock::AMP, HartreeFock::Construct_ME.
Mat<T> Interaction< T >::OBME[IsoSpin_Z][IsoSpin_Z]
Referenced by Interaction< T >::Basis_Transform, HartreeFock::Diagonalization, HartreeFock::AMP, HartreeFock::Construct_ME.
Coupled_State* Interaction< T >::Orbit
Referenced by Interaction< T >::Interaction.
int Interaction< T >::Mass_Num
double Interaction< T >::hbar_omiga
Interaction< T >::Interaction()
Interaction< T >::Interaction(string space, string ME, int A)
References Interaction< T >::Read_Orbit_Iso, Interaction< T >::Dimension_J, Interaction< T >::Orbit, Interaction< T >::Setup_Uncoupled_States_Iso, Interaction< T >::J_scheme, Interaction< T >::Read_Interaction_Iso, Interaction< T >::Construct_Interaction_Iso, Interaction< T >::Read_Orbit_PN, Interaction< T >::IsoSpin_Z, Interaction< T >::Setup_Uncoupled_States_PN, Interaction< T >::Read_Interaction_PN, Interaction< T >::Construct_Interaction_PN.
Interaction< T >::~Interaction()
void Interaction< T >::unpack(int num, int &i, int &j, int &k, int &l)
Referenced by Interaction< T >::Basis_Transform, HartreeFock::Mean_Field, HartreeFock::Hamiltonian, HartreeFock::Construct_ME.
void Interaction< T >::pack(int i, int j, int k, int l, int &num)
void Interaction< T >::Read_Orbit_Iso(string space)
Read J orbit in isospin representation.
J_Orbit
References J_Orbit::n.
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Read_Orbit_PN(string space)
Read J orbit in proton-neutron representation.
J_Orbit
References J_Orbit::n.
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Read_Interaction_Iso(string ME)
Read OBME and TBME in isospin representation.
MartrixElements OBME TBME J scheme
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Read_Interaction_PN(string ME)
Read OBME and TBME in proton-neutron representation.
MartrixElements OBME TBME J scheme
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Construct_Interaction_Iso()
Construct interaction in isospin representation.
TBME J scheme TBME M scheme
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Construct_Interaction_PN()
Construct interaction in proton-neutron representation.
TBME J scheme TBME M scheme
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Setup_Uncoupled_States_Iso(J_Orbit *J, int dim, Coupled_State *vtbme)
Setup TBME and uncoupled states in isospin representation.
J_Orbit TBME space
References J_Orbit::j, Coupled_State::orbit, Coupled_State::jmax, Coupled_State::jmin, Coupled_State::v.
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Setup_Uncoupled_States_PN(J_Orbit **Jstates, int *dim, Coupled_State *vtbme)
Setup TBME and uncoupled states in proton-neutron representation.
J_Orbit TBME space
References J_Orbit::j, Coupled_State::orbit, Coupled_State::jmax, Coupled_State::jmin, Coupled_State::v.
Referenced by Interaction< T >::Interaction.
void Interaction< T >::Basis_Transform(Interaction< T3 > &force, T1 *psil, T2 *psir)
References Interaction< T >::OBME, Interaction< T >::index, Interaction< T >::unpack, Interaction< T >::TBME.
Referenced by Nucleus::Spectral.